version: '2'

services:
    db:
        build: mysql
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        ports:
            - 3308:3308
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build: php7-fpm
        environment:
            SYMFONY_APP_PATH: ${SYMFONY_APP_PATH}
            SYMFONY_ENV: ${SYMFONY_ENV}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs

    nginx:
        build: nginx
        ports:
            - 8080:8080
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        environment:
            NGINX_HOST: ${NGINX_HOST}
            NGINX_ALIAS: ${NGINX_ALIAS}